name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
jobs:
  build:
      runs-on: ubuntu-latest
    # runs-on: ${{matrix.os}}

    # strategy:
    #   matrix:
    #       os: [ubuntu-latest, windows-latest, macOS-latest]
#          node-version: [14.x, 16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.os }}
      uses: actions/setup-node@v3
      # with:
      #   node-version: ${{ matrix.node-version }}
      #   cache: 'npm'
    - run: npm install
    - run: npm ci
    - run: npm run build --if-present
    # - run: npm install --save-dev jest
    # - run: npm test
    # - name: Build and Push Docker Image
    #     uses: docker/login-action@v2
    #     with:
    #       image: iyinka/cicd-demo-app
    #       registry: docker.io
    #       username: ${{ secrets.DOCKERHUB_USERNAME }}
    #       password: ${{ secrets.DOCKERHUB_PASSWORD }}
      # -
      #   name: Set up QEMU
      #   uses: docker/setup-qemu-action@v2
      # -
      #   name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v2
      # -
      #   name: Login to Docker Hub
      #   uses: docker/login-action@v2
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_PASSWORD }}
      # -
      #   name: Build and push
      #   uses: docker/build-push-action@v4
      #   with:
      #     context: .
      #     push: true
      #     tags: iyinka/cicd-demo-app:latest